import { useEffect, useMemo, useState } from 'react';
import { LogOut, Plus, WalletCards } from 'lucide-react';
import LegacyApp from './App.jsx';
import { api, clearToken, formatMoney, getToken } from './api.js';

const statusLabels = { novo: 'Novo', preparo: 'Em preparo', saiu_entrega: 'Saiu para entrega', concluido: 'Concluido', cancelado: 'Cancelado' };
const paymentLabels = { dinheiro: 'Dinheiro', pix: 'PIX', cartao: 'Cartao', fiado: 'Fiado' };
const tabs = [['dashboard', 'Dashboard'], ['orders', 'Pedidos'], ['new-order', 'Pedido no balcao'], ['products', 'Produtos'], ['finance', 'Financeiro'], ['customers', 'Clientes'], ['settings', 'Configuracoes']];

function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function StatusBadge({ status }) { return <span className={`badge ${status}`}>{statusLabels[status] || status}</span>; }

function AdminPremium() {
  const [tab, setTab] = useState('dashboard');
  const [orders, setOrders] = useState([]);
  const [products, setProducts] = useState([]);
  const [categories, setCategories] = useState([]);
  const [summary, setSummary] = useState(null);
  const [dashboard, setDashboard] = useState(null);
  const [expenses, setExpenses] = useState([]);
  const [customers, setCustomers] = useState([]);
  const [cash, setCash] = useState({ register: null, totals: null, movements: [] });
  const [settings, setSettings] = useState(null);
  const [report, setReport] = useState(null);
  const [message, setMessage] = useState('');
  const [expense, setExpense] = useState({ description: '', amount: '', category: 'Geral', payment_method: 'dinheiro' });
  const [movement, setMovement] = useState({ movement_type: 'entrada', description: '', amount: '', payment_method: 'dinheiro' });
  const [openValue, setOpenValue] = useState('0');
  const [closeValue, setCloseValue] = useState('0');
  const [productForm, setProductForm] = useState({ category_id: '', name: '', description: '', price: '', product_type: 'hotdog', sort_order: 0, is_active: true });
  const [manualCustomer, setManualCustomer] = useState({ name: '', phone: '', address: '', reference: '', neighborhood: '' });
  const [manualOrder, setManualOrder] = useState({ delivery_type: 'entrega', payment_method: 'dinheiro', payment_status: 'pendente', order_source: 'balcao', notes: '', items: [{ product_id: '', quantity: 1, extras: [] }] });
  const activeProducts = useMemo(() => products.filter((p) => Number(p.is_active) === 1 && p.product_type !== 'adicional'), [products]);

  async function loadAdmin() {
    try {
      const [orderData, productData, categoryData, summaryData, dashboardData, settingsData, expenseData, cashData, customerData, reportData] = await Promise.all([
        api.admin.get('/api/admin/orders'), api.admin.get('/api/admin/products'), api.admin.get('/api/admin/categories'), api.admin.get('/api/admin/finance/summary'), api.admin.get('/api/admin/dashboard'), api.admin.get('/api/admin/settings'), api.admin.get('/api/admin/finance/expenses'), api.admin.get('/api/admin/finance/cash/current'), api.admin.get('/api/admin/customers'), api.admin.get('/api/admin/reports/sales')
      ]);
      setOrders(orderData); setProducts(productData); setCategories(categoryData); setSummary(summaryData); setDashboard(dashboardData); setSettings(settingsData); setExpenses(expenseData); setCash(cashData); setCustomers(customerData); setReport(reportData);
    } catch (error) { setMessage(error.message); }
  }

  useEffect(() => { loadAdmin(); const timer = setInterval(loadAdmin, 15000); return () => clearInterval(timer); }, []);

  async function updateStatus(orderId, status, payment_status) { await api.admin.patch(`/api/admin/orders/${orderId}/status-flow`, { status, payment_status }); await loadAdmin(); }
  async function updatePayment(orderId, payment_status) { await api.admin.patch(`/api/admin/orders/${orderId}/payment-flow`, { payment_status }); await loadAdmin(); }
  async function saveProduct(event) { event.preventDefault(); await api.admin.post('/api/admin/products', { ...productForm, category_id: Number(productForm.category_id), price: Number(productForm.price), sort_order: Number(productForm.sort_order || 0), is_active: true }); setProductForm({ category_id: '', name: '', description: '', price: '', product_type: 'hotdog', sort_order: 0, is_active: true }); await loadAdmin(); }
  async function saveExpense(event) { event.preventDefault(); await api.admin.post('/api/admin/finance/expenses', { ...expense, amount: Number(expense.amount) }); setExpense({ description: '', amount: '', category: 'Geral', payment_method: 'dinheiro' }); await loadAdmin(); }
  async function saveMovement(event) { event.preventDefault(); await api.admin.post('/api/admin/finance/cash/movements', { ...movement, amount: Number(movement.amount) }); setMovement({ movement_type: 'entrada', description: '', amount: '', payment_method: 'dinheiro' }); await loadAdmin(); }
  async function openCash(event) { event.preventDefault(); await api.admin.post('/api/admin/finance/cash/open', { opening_amount: Number(openValue || 0) }); await loadAdmin(); }
  async function closeCash(event) { event.preventDefault(); await api.admin.post('/api/admin/finance/cash/close', { closing_amount: Number(closeValue || 0) }); await loadAdmin(); }
  async function saveSettings(event) { event.preventDefault(); await api.admin.put('/api/admin/settings/premium', { ...settings, delivery_fee: Number(settings.delivery_fee || 0), minimum_order: Number(settings.minimum_order || 0), estimated_delivery_minutes: Number(settings.estimated_delivery_minutes || 35), is_open: Boolean(Number(settings.is_open)), allow_whatsapp_redirect: Boolean(Number(settings.allow_whatsapp_redirect)) }); setMessage('Configuracoes salvas.'); await loadAdmin(); }
  async function createManualOrder(event) { event.preventDefault(); await api.admin.post('/api/admin/orders', { ...manualOrder, customer: manualCustomer, items: manualOrder.items.map((item) => ({ product_id: Number(item.product_id), quantity: Number(item.quantity || 1), extras: [], notes: '' })) }); setManualCustomer({ name: '', phone: '', address: '', reference: '', neighborhood: '' }); setManualOrder({ delivery_type: 'entrega', payment_method: 'dinheiro', payment_status: 'pendente', order_source: 'balcao', notes: '', items: [{ product_id: '', quantity: 1, extras: [] }] }); setMessage('Pedido criado no painel.'); await loadAdmin(); }
  function updateManualItem(index, field, value) { setManualOrder((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) })); }

  return <main className="admin-page">
    <div className="admin-header"><div><span className="eyebrow">Painel administrativo</span><h2>Central do Hot Dog do Vagner</h2></div><div className="admin-actions"><button className="btn-secondary" onClick={() => { window.location.href = '/'; }}>Cardapio</button><button className="btn-secondary" onClick={loadAdmin}>Atualizar</button><button className="btn-secondary" onClick={() => { clearToken(); window.location.reload(); }}><LogOut size={16} /> Sair</button></div></div>
    <div className="admin-tabs">{tabs.map(([key, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}</div>
    {message && <p className="notice">{message}</p>}
    {tab === 'dashboard' && <><section className="cards"><Metric label="Faturamento hoje" value={formatMoney(summary?.gross_today)} /><Metric label="Recebido hoje" value={formatMoney(summary?.paid_today)} /><Metric label="Pendente" value={formatMoney(summary?.pending_today)} /><Metric label="Liquido hoje" value={formatMoney(summary?.net_today)} /></section><section className="admin-grid"><div className="panel"><div className="panel-title"><h3>Fila de pedidos</h3></div><div className="status-grid">{Object.keys(statusLabels).map((status) => <div className="status-box" key={status}><StatusBadge status={status} /><strong>{dashboard?.status_counts?.find((item) => item.status === status)?.total || 0}</strong></div>)}</div></div><div className="panel"><div className="panel-title"><h3>Produtos mais vendidos hoje</h3></div><div className="mini-list">{dashboard?.top_products?.map((item) => <span key={item.name}>{item.name} <strong>{item.quantity}x</strong></span>)}{(!dashboard?.top_products || dashboard.top_products.length === 0) && <p className="muted">Ainda nao houve vendas hoje.</p>}</div></div></section></>}
    {tab === 'orders' && <section className="panel wide-panel"><div className="panel-title"><h3>Pedidos em tempo real</h3><button className="btn-secondary" onClick={loadAdmin}>Atualizar</button></div><div className="orders-list">{orders.map((order) => <article className="order-card" key={order.id}><div className="order-head"><div><strong>{order.public_code || `#${order.id}`} - {order.customer_name}</strong><small>{order.customer_phone} | {order.delivery_type} | {paymentLabels[order.payment_method] || order.payment_method} | {order.payment_status}</small><small>{order.customer_address} {order.customer_neighborhood ? `- ${order.customer_neighborhood}` : ''}</small>{order.notes && <small>Obs.: {order.notes}</small>}</div><div className="order-total"><StatusBadge status={order.status} /><strong>{formatMoney(order.total)}</strong></div></div><div className="order-items">{order.items?.map((item) => <span key={item.id}>{item.quantity}x {item.name}</span>)}</div><div className="order-actions"><button onClick={() => updateStatus(order.id, 'preparo')}>Aceitar/preparar</button><button onClick={() => updateStatus(order.id, 'saiu_entrega')}>Saiu entrega</button><button onClick={() => updateStatus(order.id, 'concluido', 'pago')}>Concluir e pagar</button><button onClick={() => updatePayment(order.id, 'pago')}>Marcar pago</button><button onClick={() => updateStatus(order.id, 'cancelado', 'cancelado')}>Cancelar</button></div></article>)}{orders.length === 0 && <p className="muted">Nenhum pedido encontrado.</p>}</div></section>}
    {tab === 'new-order' && <section className="panel"><div className="panel-title"><h3><Plus size={18} /> Pedido manual / balcao</h3></div><form onSubmit={createManualOrder} className="stack-form"><div className="form-grid"><input placeholder="Nome do cliente" value={manualCustomer.name} onChange={(e) => setManualCustomer({ ...manualCustomer, name: e.target.value })} required /><input placeholder="Telefone" value={manualCustomer.phone} onChange={(e) => setManualCustomer({ ...manualCustomer, phone: e.target.value })} required /><input placeholder="Endereco" value={manualCustomer.address} onChange={(e) => setManualCustomer({ ...manualCustomer, address: e.target.value })} /><input placeholder="Bairro" value={manualCustomer.neighborhood} onChange={(e) => setManualCustomer({ ...manualCustomer, neighborhood: e.target.value })} /></div>{manualOrder.items.map((item, index) => <div className="form-grid" key={index}><select value={item.product_id} onChange={(e) => updateManualItem(index, 'product_id', e.target.value)} required><option value="">Produto</option>{activeProducts.map((product) => <option key={product.id} value={product.id}>{product.name} - {formatMoney(product.price)}</option>)}</select><input type="number" min="1" value={item.quantity} onChange={(e) => updateManualItem(index, 'quantity', e.target.value)} /></div>)}<button type="button" className="btn-secondary" onClick={() => setManualOrder((current) => ({ ...current, items: [...current.items, { product_id: '', quantity: 1, extras: [] }] }))}>Adicionar item</button><div className="form-grid"><select value={manualOrder.delivery_type} onChange={(e) => setManualOrder({ ...manualOrder, delivery_type: e.target.value })}><option value="entrega">Entrega</option><option value="retirada">Retirada</option></select><select value={manualOrder.payment_method} onChange={(e) => setManualOrder({ ...manualOrder, payment_method: e.target.value })}><option value="dinheiro">Dinheiro</option><option value="pix">PIX</option><option value="cartao">Cartao</option><option value="fiado">Fiado</option></select><select value={manualOrder.payment_status} onChange={(e) => setManualOrder({ ...manualOrder, payment_status: e.target.value })}><option value="pendente">Pendente</option><option value="pago">Pago</option></select><select value={manualOrder.order_source} onChange={(e) => setManualOrder({ ...manualOrder, order_source: e.target.value })}><option value="balcao">Balcao</option><option value="admin">Admin</option><option value="whatsapp">WhatsApp</option></select></div><textarea placeholder="Observacoes" value={manualOrder.notes} onChange={(e) => setManualOrder({ ...manualOrder, notes: e.target.value })} /><button className="btn-primary">Criar pedido</button></form></section>}
    {tab === 'products' && <section className="admin-grid"><div className="panel"><div className="panel-title"><h3><Plus size={18} /> Novo produto</h3></div><form onSubmit={saveProduct} className="stack-form"><select value={productForm.category_id} onChange={(e) => setProductForm({ ...productForm, category_id: e.target.value })} required><option value="">Categoria</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select><input placeholder="Nome do produto" value={productForm.name} onChange={(e) => setProductForm({ ...productForm, name: e.target.value })} required /><textarea placeholder="Descricao" value={productForm.description} onChange={(e) => setProductForm({ ...productForm, description: e.target.value })} /><input placeholder="Preco" type="number" step="0.01" value={productForm.price} onChange={(e) => setProductForm({ ...productForm, price: e.target.value })} required /><select value={productForm.product_type} onChange={(e) => setProductForm({ ...productForm, product_type: e.target.value })}><option value="hotdog">Hot dog</option><option value="suco">Suco</option><option value="bebida">Bebida</option><option value="adicional">Adicional</option></select><button className="btn-primary">Salvar produto</button></form></div><div className="panel"><div className="panel-title"><h3>Produtos cadastrados</h3></div><div className="product-table">{products.map((product) => <div className="product-row" key={product.id}><div><strong>{product.name}</strong><small>{product.category_name} | {product.product_type}</small></div><strong>{formatMoney(product.price)}</strong><span>{product.is_active ? 'Ativo' : 'Inativo'}</span></div>)}</div></div></section>}
    {tab === 'finance' && <section className="admin-grid"><div className="panel"><div className="panel-title"><h3>Caixa</h3></div>{cash?.register ? <><p className="notice">Caixa aberto. Saldo previsto: <strong>{formatMoney(cash.totals?.saldo)}</strong></p><div className="cards compact"><Metric label="Entradas" value={formatMoney(cash.totals?.entradas)} /><Metric label="Saidas" value={formatMoney(cash.totals?.saidas)} /></div><form onSubmit={closeCash} className="stack-form"><input type="number" step="0.01" value={closeValue} onChange={(e) => setCloseValue(e.target.value)} placeholder="Valor contado no fechamento" /><button className="btn-primary">Fechar caixa</button></form></> : <form onSubmit={openCash} className="stack-form"><input type="number" step="0.01" value={openValue} onChange={(e) => setOpenValue(e.target.value)} placeholder="Troco inicial" /><button className="btn-primary">Abrir caixa</button></form>}<hr /><form onSubmit={saveMovement} className="stack-form"><select value={movement.movement_type} onChange={(e) => setMovement({ ...movement, movement_type: e.target.value })}><option value="entrada">Entrada</option><option value="saida">Saida</option></select><input placeholder="Descricao" value={movement.description} onChange={(e) => setMovement({ ...movement, description: e.target.value })} required /><input placeholder="Valor" type="number" step="0.01" value={movement.amount} onChange={(e) => setMovement({ ...movement, amount: e.target.value })} required /><button className="btn-secondary">Registrar movimento</button></form></div><div className="panel"><div className="panel-title"><h3><WalletCards size={18} /> Nova despesa</h3></div><form onSubmit={saveExpense} className="stack-form"><input placeholder="Descricao" value={expense.description} onChange={(e) => setExpense({ ...expense, description: e.target.value })} required /><input placeholder="Valor" type="number" step="0.01" value={expense.amount} onChange={(e) => setExpense({ ...expense, amount: e.target.value })} required /><input placeholder="Categoria" value={expense.category} onChange={(e) => setExpense({ ...expense, category: e.target.value })} /><button className="btn-primary">Cadastrar saida</button></form><div className="mini-list">{expenses.slice(0, 8).map((item) => <span key={item.id}>{item.description} <strong>{formatMoney(item.amount)}</strong></span>)}</div></div></section>}
    {tab === 'customers' && <section className="panel"><div className="panel-title"><h3>Clientes</h3></div><div className="product-table">{customers.map((customer) => <div className="product-row" key={customer.id}><div><strong>{customer.name}</strong><small>{customer.phone} | {customer.address}</small></div><span>{customer.orders_count} pedidos</span><strong>{formatMoney(customer.total_spent)}</strong></div>)}</div></section>}
    {tab === 'settings' && settings && <section className="admin-grid"><div className="panel"><div className="panel-title"><h3>Configuracoes do negocio</h3></div><form onSubmit={saveSettings} className="stack-form"><input value={settings.business_name || ''} onChange={(e) => setSettings({ ...settings, business_name: e.target.value })} placeholder="Nome do negocio" /><input value={settings.phone || ''} onChange={(e) => setSettings({ ...settings, phone: e.target.value })} placeholder="Telefone" /><input value={settings.whatsapp || ''} onChange={(e) => setSettings({ ...settings, whatsapp: e.target.value })} placeholder="WhatsApp com DDI" /><input value={settings.address || ''} onChange={(e) => setSettings({ ...settings, address: e.target.value })} placeholder="Endereco" /><input type="number" step="0.01" value={settings.delivery_fee || 0} onChange={(e) => setSettings({ ...settings, delivery_fee: e.target.value })} placeholder="Taxa entrega" /><input type="number" step="0.01" value={settings.minimum_order || 0} onChange={(e) => setSettings({ ...settings, minimum_order: e.target.value })} placeholder="Pedido minimo" /><input value={settings.pix_key || ''} onChange={(e) => setSettings({ ...settings, pix_key: e.target.value })} placeholder="Chave PIX" /><input type="number" value={settings.estimated_delivery_minutes || 35} onChange={(e) => setSettings({ ...settings, estimated_delivery_minutes: e.target.value })} placeholder="Previsao em minutos" /><textarea value={settings.delivery_area_text || ''} onChange={(e) => setSettings({ ...settings, delivery_area_text: e.target.value })} placeholder="Areas/bairros de entrega" /><select value={Number(settings.is_open)} onChange={(e) => setSettings({ ...settings, is_open: e.target.value })}><option value="1">Aberto</option><option value="0">Fechado</option></select><select value={Number(settings.allow_whatsapp_redirect)} onChange={(e) => setSettings({ ...settings, allow_whatsapp_redirect: e.target.value })}><option value="1">Abrir WhatsApp apos pedido</option><option value="0">Nao abrir WhatsApp</option></select><button className="btn-primary">Salvar configuracoes</button></form></div><div className="panel"><div className="panel-title"><h3>Relatorio de hoje</h3></div><div className="mini-list"><span>Vendas <strong>{formatMoney(report?.summary?.gross)}</strong></span><span>Recebido <strong>{formatMoney(report?.summary?.paid)}</strong></span><span>Despesas <strong>{formatMoney(report?.summary?.expenses)}</strong></span><span>Liquido <strong>{formatMoney(report?.summary?.net)}</strong></span></div></div></section>}
  </main>;
}

export default function PremiumApp() {
  if (!window.location.pathname.includes('admin')) return <LegacyApp />;
  if (!getToken()) return <LegacyApp />;
  return <div><header className="topbar"><div><span className="eyebrow">Pedidos online</span><h1>Hot Dog do Vagner</h1></div><nav><button onClick={() => { window.location.href = '/'; }}>Cardapio</button><button className="active">Admin</button></nav></header><AdminPremium /></div>;
}
